# Generated by Django 5.2.10 on 2026-05-01 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formation', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commande',
            name='moneroo_payment_url',
        ),
        migrations.RemoveField(
            model_name='commande',
            name='moneroo_transaction_id',
        ),
        migrations.AddField(
            model_name='commande',
            name='operateur_paiement',
            field=models.CharField(blank=True, choices=[('airtel', 'Airtel Money'), ('mtn', 'Mobile Money (MTN)'), ('orange', 'Orange Money')], max_length=20, null=True, verbose_name='Opérateur de paiement'),
        ),
        migrations.AddField(
            model_name='commande',
            name='reference_paiement',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Référence / Preuve paiement'),
        ),
    ]
