# Generated by Django 5.2.10 on 2026-05-08 09:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formation', '0002_remove_commande_moneroo_payment_url_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormationDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description_complete', models.TextField(verbose_name='Description complète')),
                ('accompagnement', models.TextField(blank=True, verbose_name='Accompagnement')),
                ('ce_que_vous_apprenez', models.TextField(blank=True, verbose_name='Ce que vous apprendrez')),
                ('public_cible', models.TextField(blank=True, verbose_name='Public cible')),
                ('bonus', models.TextField(blank=True, verbose_name='Bonus')),
                ('formation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='detail', to='formation.formation')),
            ],
        ),
        migrations.CreateModel(
            name='FormationImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='formation/details/')),
                ('titre', models.CharField(blank=True, max_length=200)),
                ('formation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='formation.formation')),
            ],
        ),
    ]
