# Generated by Django 5.2.10 on 2026-05-08 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formation', '0003_formationdetail_formationimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='formationdetail',
            name='competences_a_developper',
            field=models.TextField(blank=True, verbose_name='Compétences à développer'),
        ),
    ]
