# Generated by Django 5.2.10 on 2026-05-18 15:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formation', '0004_formationdetail_competences_a_developper'),
    ]

    operations = [
        migrations.AddField(
            model_name='formation',
            name='prix_promo',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Prix promotionnel'),
        ),
    ]
