# Generated by Django 5.2.10 on 2026-05-31 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formation', '0005_formation_prix_promo'),
    ]

    operations = [
        migrations.AddField(
            model_name='commande',
            name='senepay_status',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='commande',
            name='senepay_transaction_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='commande',
            name='session_token',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
