# Generated by Django 5.2.10 on 2026-08-14 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formation', '0006_commande_senepay_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='formation',
            name='drive_folder_id',
            field=models.CharField(blank=True, help_text="L'ID dans l'URL du dossier : drive.google.com/drive/folders/[CET_ID]", max_length=100, verbose_name='ID du dossier Google Drive'),
        ),
    ]
